"""
Batch-generate all-MiniLM-L6-v2 embeddings for every doc chunk and store them.

Embeds the full body text of each documentation page (not just titles)
using paragraph-based chunking for scalable vector search.

Two modes:

  1. SQL mode (default) — prints INSERT statements for the SQL Editor.
  2. Direct mode — writes directly via PostgreSQL.

       python api/enrich_docs.py
       python api/enrich_docs.py --direct
"""

import argparse
import json
import os
import re
import sys
import textwrap

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from api.chunk_docs import chunk_text  # noqa: E402
from api.embed import embed_many  # noqa: E402


def strip_frontmatter(text: str) -> str:
    lines = text.split("\n")
    body_start = 0
    for i, line in enumerate(lines):
        if line.startswith(("source:", "title:", "source_hash:", "discovered_from:", "#")) or line.strip() == "":
            body_start = i + 1
        else:
            break
    return "\n".join(lines[body_start:])


def vector_literal(values: list[float]) -> str:
    return "[" + ",".join(str(v) for v in values) + "]"


def process_all_items(sql_output: bool = True, output_file: str | None = None):
    manifest_path = os.path.join(_PROJECT_ROOT, "skills", "polygres", "references", "upstream", "manifest.json")
    pages_dir = os.path.join(_PROJECT_ROOT, "skills", "polygres", "references", "upstream", "pages")

    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    all_chunks: list[dict] = []
    for item in manifest["items"]:
        doc_id = os.path.splitext(os.path.basename(item["path"]))[0]
        title = item["title"].replace(" | Polygres", "").strip()
        md_path = os.path.join(pages_dir, item["path"])

        if not os.path.exists(md_path):
            print(f"-- WARNING: {md_path} not found, skipping", file=sys.stderr)
            continue

        md_text = open(md_path, encoding="utf-8").read()
        body = strip_frontmatter(md_text)
        full_text = f"{title}\n\n{body}"

        chunks = chunk_text(full_text)
        for idx, chunk in enumerate(chunks):
            all_chunks.append({
                "chunk_id": f"chunk_{doc_id}_{idx}",
                "doc_id": doc_id,
                "content": chunk,
                "chunk_index": idx,
            })

    if not all_chunks:
        print("-- No chunks to embed.", file=sys.stderr)
        return

    print(f"-- {len(all_chunks)} chunks from {len(manifest['items'])} pages", flush=True)

    chunk_index_path = os.path.join(os.path.dirname(__file__), "chunk_index.json")
    chunk_index = {c["chunk_id"]: c["content"] for c in all_chunks}
    json.dump(chunk_index, open(chunk_index_path, "w", encoding="utf-8"), ensure_ascii=False)
    print(f"-- Wrote chunk index: {chunk_index_path}", file=sys.stderr)

    texts = [c["content"] for c in all_chunks]
    embeddings = embed_many(texts)

    if sql_output:
        conn = None
        _write = (lambda s: print(s)) if output_file is None else (lambda s: output_file.write(s + "\n"))
        _write("-- Auto-generated by enrich_docs.py")
        _write("-- Drops + recreates doc_chunks with vector(384) for all-MiniLM-L6-v2.")
        _write("-- Run this in the Polygres SQL Editor.")
        _write("")
        _write("DROP TABLE IF EXISTS doc_chunks CASCADE;")
        _write("")
        _write("CREATE TABLE doc_chunks (")
        _write("  id            text PRIMARY KEY,")
        _write("  doc_id        text NOT NULL REFERENCES docs_pages(id) ON DELETE CASCADE,")
        _write("  content       text NOT NULL,")
        _write("  chunk_index   integer NOT NULL,")
        _write("  embedding     vector(384)")
        _write(");")
        _write("")
    else:
        import psycopg
        _write = None
        direct_url = os.environ["POLYGRES_DIRECT_URL"]
        conn = psycopg.connect(direct_url)

    for chunk, emb in zip(all_chunks, embeddings):
        lit = vector_literal(emb)

        if sql_output:
            escaped = chunk["content"].replace("'", "''")
            _write(
                textwrap.dedent(f"""\
                INSERT INTO doc_chunks (id, doc_id, content, chunk_index, embedding) VALUES
                  ('{chunk['chunk_id']}', '{chunk['doc_id']}', '{escaped}', {chunk['chunk_index']}, '{lit}'::vector)
                ON CONFLICT (id) DO UPDATE SET embedding = EXCLUDED.embedding;
                """).rstrip()
            )
        else:
            conn.cursor().execute(
                "INSERT INTO doc_chunks (id, doc_id, content, chunk_index, embedding) "
                "VALUES (%s, %s, %s, %s, %s::vector) "
                "ON CONFLICT (id) DO UPDATE SET embedding = EXCLUDED.embedding",
                (chunk["chunk_id"], chunk["doc_id"], chunk["content"], chunk["chunk_index"], lit),
            )

    if conn:
        conn.commit()
        conn.close()
        print(f"Done. {len(all_chunks)} rows written.")

    print(f"-- {len(all_chunks)} chunks processed")


def index_only():
    manifest_path = os.path.join(_PROJECT_ROOT, "skills", "polygres", "references", "upstream", "manifest.json")
    pages_dir = os.path.join(_PROJECT_ROOT, "skills", "polygres", "references", "upstream", "pages")

    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    chunk_index = {}
    for item in manifest["items"]:
        doc_id = os.path.splitext(os.path.basename(item["path"]))[0]
        title = item["title"].replace(" | Polygres", "").strip()
        md_path = os.path.join(pages_dir, item["path"])
        if not os.path.exists(md_path):
            continue
        md_text = open(md_path, encoding="utf-8").read()
        body = strip_frontmatter(md_text)
        full_text = f"{title}\n\n{body}"
        for idx, chunk in enumerate(chunk_text(full_text)):
            chunk_index[f"chunk_{doc_id}_{idx}"] = chunk

    path = os.path.join(os.path.dirname(__file__), "chunk_index.json")
    json.dump(chunk_index, open(path, "w", encoding="utf-8"), ensure_ascii=False)
    print(f"Wrote {len(chunk_index)} entries to {path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Enrich doc sections with all-MiniLM-L6-v2 embeddings.")
    parser.add_argument(
        "--direct",
        action="store_true",
        help="Write directly via PostgreSQL (requires POLYGRES_DIRECT_URL).",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Write SQL output to a file instead of stdout (avoids shell encoding issues).",
    )
    parser.add_argument(
        "--index-only",
        action="store_true",
        help="Only generate chunk_index.json from source files (no embeddings, no DB).",
    )
    args = parser.parse_args()
    if args.index_only:
        index_only()
        sys.exit(0)
    fh = None
    if args.output:
        fh = open(args.output, "w", encoding="utf-8")
    try:
        process_all_items(sql_output=not args.direct, output_file=fh)
    finally:
        if fh:
            fh.close()
